config/routes.rb
I5s::Application.routes.draw do

  class PageConstraint
    def matches?(request)
      path = request.original_fullpath.clone
      path[0] = ''
      puts CGI::unescape(path)
      @page = Page.where(:path => CGI::unescape(path))
      @page.present?
    end
  end

  namespace :admin do
    resources :pages
    resources :uploads
  end

  get "*path" => "pages#show", :constraints => PageConstraint.new, format: false

  root :to => "pages#show"

end

app/models/page.rb
class Page < ActiveRecord::Base
  before_save :normilize
  before_validation :normilize

  validates :path, :uniqueness => {case_sensitive: false}

  def normilize
    self.path = self.path.gsub(/^\/+/, '')
    self.path = self.path.gsub(/\/+$/, '')
    self.path = self.path.gsub(/^\s+/, '')
    self.path = self.path.gsub(/\s+$/, '')
  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < PagesController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: "nimda"


  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to [:admin, @page], notice: 'Страница была успешно создана.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to [:admin, @page], notice: 'Страница была успешно изменена.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to admin_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:path, :title, :content)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page

  def show
    @meta_title = @page.title
    @meta_canonical = '/' + @page.path
  end

  private

  def set_page
    path = request.original_fullpath
    path[0] = ''
    @page = Page.where(:path => CGI::unescape(path)).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/pages/_form.html.erb
<div class="row">

  <div class="col-lg-12">
    
    <%= form_for @page, url: [:admin, @page], html: { class: 'form-horizontal' } do |f| %>

      <% if @page.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@page.errors.count, "error") %> </h4>

          <ul>
          <% @page.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :path, class: "col-sm-1 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :path, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :title, class: "col-sm-1 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= f.text_area :content %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= f.submit nil, class: "btn btn-lg btn-primary"  %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'К списку', admin_pages_path %>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/admin/pages/edit.html.erb
<h1 class="page-header">Редактирование страницы</h1>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h1 class="page-header">Страницы</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= Page.human_attribute_name(:path) %></th>
        <th><%= Page.human_attribute_name(:title) %></th>
        <th><%= Page.human_attribute_name(:content) %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.path %></td>
          <td><%= page.title %></td>
          <td><%= truncate(strip_tags(page.content), length: 120) %></td>
          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, admin_page_path(page), class: "btn btn-default" %></td>
          <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_page_path(page), class: "btn btn-warning" %></td>
          <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_page_path(page), method: :delete, data: { confirm: 'Уверены что хотите удалить страницу?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Новая страница', new_admin_page_path, class: "btn btn-lg btn-primary" %>

<br>
<br>

app/views/admin/pages/new.html.erb
<h1 class="page-header">Новая страница</h1>

<%= render 'form' %>

app/views/admin/pages/show.html.erb
<h1 class="page-header">Просмотр страницы</h1>

<% if notice %>
  <div class="alert alert-success alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= notice %>
  </div>
<% end %>

<h3>
  <%= link_to "/#{@page.path}", target: "_blank" do %>
    <%= root_url + @page.path %>
  <% end %>
</h3>

<h3>
  <%= @page.title %>
</h3>

<%== @page.content %>

<br />
<br />

<%= link_to 'Новая страница', new_admin_page_path(@page), class: "btn btn-primary" %>
<%= link_to 'Редактировать', edit_admin_page_path(@page), class: "btn btn-warning" %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'К списку', admin_pages_path %>

<br />
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= @meta_title %></title>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <meta name="google-site-verification" content="XU7kvWvafsnNnJ-rkM-jnJOtkD00lQG8QZpLlzlR5po" />
  <meta name='yandex-verification' content='62d18fdc1561b0a0' />

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- CKEDITOR -->
  <script src="/ckeditor/ckeditor.js"></script>
  <script src="/ckeditor/adapters/jquery.js"></script>
  <!-- /CKEDITOR -->

  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <!-- /BOOTSTRAP -->

  <!-- FONT AWESOME -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <!-- /FONT AWESOME -->

</head>
<body>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/_form.html.erb
<div class="row">

  <div class="col-lg-12">
    
    <%= form_for @page, url: [:admin, @page], html: { class: 'form-horizontal' } do |f| %>

      <% if @page.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

          <ul>
          <% @page.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :path, class: "col-sm-1 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :path, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :title, class: "col-sm-1 control-label" %>
        <div class="col-sm-6">
          <%= f.text_field :title, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= f.text_area :content %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <%= f.submit nil, class: "btn btn-lg btn-primary"  %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'К списку', admin_pages_path %>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/pages/index.html.erb
<h1 class="page-header">Страницы</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th><%= Page.human_attribute_name(:path) %></th>
        <th><%= Page.human_attribute_name(:title) %></th>
        <th><%= Page.human_attribute_name(:content) %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.path %></td>
          <td><%= page.title %></td>
          <td><%= truncate(strip_tags(page.content), length: 120) %></td>
          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, "/#{page.path}", class: "btn btn-default", target: "_blank" %></td>
          <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, admin_page_path(page), class: "btn btn-default" %></td>
          <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_admin_page_path(page), class: "btn btn-warning" %></td>
          <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, admin_page_path(page), method: :delete, data: { confirm: 'Уверены что хотите удалить страницу?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Новая страница', new_admin_page_path, class: "btn btn-lg btn-primary" %>

<br>
<br>

app/views/pages/show.html.erb
<%== @page.content %>